[BE] Milestone API 기능 구현
codesquad-member-2020/issue-tracker-09 pull request #61
Opened 2020-06-20 07:48 UTC by suhyunsim

* Milestone 목록, 생성, 수정, 삭제, picker api 구현
* picker api는 ModelMapper를 활용해서 구현한다.

2020-06-20 08:03 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/domain/Milestone.java
> +    private Integer numberOfClosedIssue;
열린/닫힌 이슈 갯수를 필드로 가지고 있는 것보다 메서드로 계산해서 가져오는 것은 어떨까요

2020-06-20 08:05 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/service/MilestoneService.java
> +            throw new ValidationException("Title can't be blank");
Exception 처리 👍👍

2020-06-20 08:06 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/service/MilestoneService.java
> +            MilestonePickerDTO milestonePickerDTO = modelMapper.map(milestone, MilestonePickerDTO.class);
modelMapper를 쓰니깐 코드중복이 없어서 너무 좋네요!! 저도 적용해서 리팩토링 할게요~~

2020-06-20 08:14 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/web/milestone/controller/MilestoneController.java
> +        } else {
else 없이 바로 써도 좋을 것 같아요!

2020-06-20 08:15 UTC, blossun requested changes
화이팅 고생 많으셨습니다!

2020-06-21 18:56 UTC, suhyunsim commented on BE/src/main/java/kr/codesquad/issuetracker09/domain/Milestone.java
> +    private Integer numberOfClosedIssue;
엔티티에서 필드로 가지고 있던 부분을 삭제하고 계산해서 가져올 수 있도록 변경했습니다!

2020-06-21 18:56 UTC, suhyunsim commented on BE/src/main/java/kr/codesquad/issuetracker09/web/milestone/controller/MilestoneController.java
> +        } else {
반영하겠습니다~

2020-06-21 18:59 UTC, suhyunsim commented
수정사항 반영했습니다!
mock 서버를 위해서 사용하던 GetMilestoneListResponseDTO를 재사용하려고 했는데 numberOfOpenIssue, numberOfClosedIssue를 계산하는 메서드의 반환형태가 Long이 되어버려서 사용하기가 어렵더라고요.
해당 사항만 다르게 반영한 DTO를 새로 생성해서 목록을 전달하도록 반영했습니다!

2020-06-22 01:17 UTC, merged