[BE] Issue Summary api 기능 구현
codesquad-member-2020/issue-tracker-09 pull request #86
Opened 2020-07-08 11:12 UTC by suhyunsim

* issue 전체 목록 조회, 생성, 수정, 열기/닫기 기능 구현
* Issue Summary api: 3, 5, 7, 8
* issue의 milestone과 label이 없을 경우 각각 null, []로 출력한다.

## 3. issue 생성
* `POST /issues` url로 issue를 생성한다.
    * RequestBody로 contents, title 내용을 담아 요청한다.
    * image url과 관련한 부분은 미구현 상태
    * title은 Not null, null일 경우 422 예외처리

## 5. issue 수정
* `PUT /issues/{issue-id}` url로 issue를 수정한다.
    * 해당 issue의 contents, title의 수정할 내용을 RequestBody에 담아 요청한다.
    * image url과 관련한 부분은 미구현 상태
    * title은 Not null, null일 경우 422 예외처리

## 7. issue 열기/닫기 
* `PATCH /issues` url로 issue를 열거나 닫는다.
    * 열거나 닫을 issue들의 리스트를 RequestBody에 담아 요청한다.
    * 닫을 때는 open 필드가 0, 열 때는 1로 요청한다.
    * 0과 1 외의 숫자가 요청으로 올 때의 예외처리 미구현

2020-07-08 13:15 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/service/IssueService.java
> +    public List<GetIssueListResponseDTO> issueListResponseDTOList(List<Issue> issues) {
재사용하기 좋게 리팩토링되었네요 🤓 👍👍

2020-07-09 01:59 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/service/IssueService.java
> +            if (issueRepository.findMilestoneIdByIssueId(issue.getId()) != null) {
Milestone id 값을 Repository에서 쿼리로 가져오네요!
issue.getMilestone().getId()으로 객체에서 가져오는 것은 어떤가요??

2020-07-09 02:28 UTC, blossun commented on BE/src/main/java/kr/codesquad/issuetracker09/service/IssueService.java
> +    public void change(PatchCloseIssueRequestDTO request) throws NotFound {
메소드명이 좀 더 명확하면 좋을 것 같아요~!!

2020-07-09 02:33 UTC, blossun requested changes
API 끝까지 완성하는 모습 👍👍👍

2020-07-10 06:11 UTC, suhyunsim commented on BE/src/main/java/kr/codesquad/issuetracker09/service/IssueService.java
> +            if (issueRepository.findMilestoneIdByIssueId(issue.getId()) != null) {
객체에서 가져오도록 수정했습니다!

2020-07-10 06:12 UTC, suhyunsim commented on BE/src/main/java/kr/codesquad/issuetracker09/service/IssueService.java
> +    public void change(PatchCloseIssueRequestDTO request) throws NotFound {
change() -> changeOpenStatus()라는 메소드명으로 수정했습니다!

2020-07-10 06:15 UTC, merged